/*
 * The MIT License
 *
 * Copyright 2023 Thiago de Souza Rogério.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package screen;

import javax.swing.JOptionPane;
import config.ModuloConexao;
import java.sql.*;

/**
 * Tela Principal(Inicial) do Sistema 
 *
 * @author Thiago de Souza Rogério 
 * @Versão 1.0
 */

public class TelaPrincipal extends javax.swing.JFrame {

    public TelaPrincipal() {
        initComponents();

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadUsu = new javax.swing.JMenuItem();
        menCadEquip = new javax.swing.JMenuItem();
        menCadCon = new javax.swing.JMenuItem();
        menCadFun = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        menRelEquip = new javax.swing.JMenuItem();
        menRelFun = new javax.swing.JMenuItem();
        menRelCha = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menOpcSobre = new javax.swing.JMenuItem();
        menOpcLogoff = new javax.swing.JMenuItem();
        menOpcFechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        menCad.setText("Cadastros");

        menCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadUsu.setText("Usuários");
        menCadUsu.setEnabled(false);
        menCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuActionPerformed(evt);
            }
        });
        menCad.add(menCadUsu);

        menCadEquip.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadEquip.setText("Equipamento");
        menCadEquip.setEnabled(false);
        menCadEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadEquipActionPerformed(evt);
            }
        });
        menCad.add(menCadEquip);

        menCadCon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadCon.setText("Contrato");
        menCadCon.setEnabled(false);
        menCadCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadConActionPerformed(evt);
            }
        });
        menCad.add(menCadCon);

        menCadFun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadFun.setText("Funcionário");
        menCadFun.setEnabled(false);
        menCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadFunActionPerformed(evt);
            }
        });
        menCad.add(menCadFun);

        jMenuBar1.add(menCad);

        menRel.setText("Relatórios");
        menRel.setEnabled(false);

        menRelEquip.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelEquip.setText("Equipamentos");
        menRelEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelEquipActionPerformed(evt);
            }
        });
        menRel.add(menRelEquip);

        menRelFun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelFun.setText("Funcionários");
        menRelFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelFunActionPerformed(evt);
            }
        });
        menRel.add(menRelFun);

        menRelCha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelCha.setText("Chamados");
        menRel.add(menRelCha);

        jMenuBar1.add(menRel);

        menOpc.setText("Opções");

        menOpcSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menOpcSobre.setText("Sobre");
        menOpcSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpcSobreActionPerformed(evt);
            }
        });
        menOpc.add(menOpcSobre);

        menOpcLogoff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menOpcLogoff.setText("Logoff");
        menOpcLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpcLogoffActionPerformed(evt);
            }
        });
        menOpc.add(menOpcLogoff);

        menOpcFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menOpcFechar.setText("Fechar");
        menOpcFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpcFecharActionPerformed(evt);
            }
        });
        menOpc.add(menOpcFechar);

        jMenuBar1.add(menOpc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento responsável em apresentar a tela de contrato
     * @param evt 
     */
    private void menCadConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadConActionPerformed
        // TODO add your handling code here:
        TelaContrato contrato = new TelaContrato();
        contrato.setVisible(true);
        Desktop.add(contrato);
    }//GEN-LAST:event_menCadConActionPerformed

    /**
     * Evento responsável em fechar o sistema por completo
     * @param evt 
     */
    private void menOpcFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpcFecharActionPerformed
        // TODO add your handling code here:

        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que desejar fechar o sistema?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menOpcFecharActionPerformed

    /**
     * Evento responsável em sair do sistema, retornando a tela de login 
     * @param evt 
     */
    private void menOpcLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpcLogoffActionPerformed
        // TODO add your handling code here:
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menOpcLogoffActionPerformed

    /**
     * Evento responsável em apresentar a tela de equiapamentos
     * @param evt 
     */
    private void menCadEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadEquipActionPerformed
        // TODO add your handling code here:
        TelaEquipamentos equipamentos = new TelaEquipamentos();
        equipamentos.setVisible(true);
        Desktop.add(equipamentos);
    }//GEN-LAST:event_menCadEquipActionPerformed

    /**
     * Evento responsável em apresentar a tela de relatório de equipamentos
     * @param evt 
     */
    private void menRelEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelEquipActionPerformed
        // TODO add your handling code here:
        TelaRelatorioEquipamento relatorio_equipamentos = new TelaRelatorioEquipamento();
        relatorio_equipamentos.setVisible(true);
        Desktop.add(relatorio_equipamentos);
    }//GEN-LAST:event_menRelEquipActionPerformed

    /**
     * Evento responsável em apresentar a tela Sobre, que contem informações do sistema, como Autor, Licença e outros
     * 
     * @param evt 
     */
    private void menOpcSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpcSobreActionPerformed
        // TODO add your handling code here:
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
        Desktop.add(sobre);
    }//GEN-LAST:event_menOpcSobreActionPerformed

    /**
     * Evento responsável em apresentar a tela de cadastro de usuários
     * @param evt 
     */
    private void menCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuActionPerformed
        // TODO add your handling code here:
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        Desktop.add(usuario);
    }//GEN-LAST:event_menCadUsuActionPerformed

    /**
     * Evento responsável em apresentar a tela de cadastro de funcionários
     * @param evt 
     */
    private void menCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadFunActionPerformed
        // TODO add your handling code here:
        TelaFuncionario funcionario = new TelaFuncionario();
        funcionario.setVisible(true);
        Desktop.add(funcionario);

    }//GEN-LAST:event_menCadFunActionPerformed

    /**
     * Evento responsável em apresentar a tela de relatório de funcionários
     * @param evt 
     */
    private void menRelFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelFunActionPerformed
        // TODO add your handling code here:]
        TelaRelatorioFuncionario rel_funcionario = new TelaRelatorioFuncionario();
        rel_funcionario.setVisible(true);
        Desktop.add(rel_funcionario);
    }//GEN-LAST:event_menRelFunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menCad;
    public static javax.swing.JMenuItem menCadCon;
    public static javax.swing.JMenuItem menCadEquip;
    public static javax.swing.JMenuItem menCadFun;
    public static javax.swing.JMenuItem menCadUsu;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenuItem menOpcFechar;
    private javax.swing.JMenuItem menOpcLogoff;
    private javax.swing.JMenuItem menOpcSobre;
    public static javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menRelCha;
    private javax.swing.JMenuItem menRelEquip;
    private javax.swing.JMenuItem menRelFun;
    // End of variables declaration//GEN-END:variables
}
